title: Sanchia de Villiers Kuun
description: A website with a blog
footer_text: Copyright 2020 Sanchia de Villiers Kuun
header_feature_image: ../uploads/pages.jpg
header_text: My Dream Blog
header_text_color: "#ffffff"
bannerheight: 20vmax
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
