title: "HAPPY, HEALTHY, VEGAN-LIVING. "
description: "Lifestyle and Recipes "
footer_text: Copyright 2020 Sanchia de Villiers Kuun
header_feature_image: ../uploads/blog-pic.jpg
header_text: "HAPPY, HEALTHY, VEGAN-LIVING. "
header_text_color: "#ffe3e3"
bannerheight: 20vmax
logo: ../uploads/img_3622.jpg
favicon: /uploads/favicon.ico
gridlayout: true
fixednavbar: false
upzoom: true
items:
  - siteurl: file:///Applications/recipe/recipe.html
    name: The Vegalicious Takeaway
    tab: true
